# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsblog', '0004_auto_20170527_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='talk',
            new_name='talks',
        ),
        migrations.AddField(
            model_name='venue',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cmsblog.Event'),
            preserve_default=False,
        ),
    ]
