# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsblog', '0005_auto_20170528_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cmsblog.Venue'),
            preserve_default=False,
        ),
    ]
